name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.5.2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.6.0'
          cache: 'pnpm'

      - name: Check Node.js version
        run: node --version

      - name: Check pnpm version
        run: pnpm --version

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          pnpm install --no-frozen-lockfile
          echo "Dependencies installed successfully"

      - name: Verify dependencies
        run: |
          echo "Verifying dependencies..."
          pnpm list --depth=0
          echo "Dependencies verified"

      - name: Test build
        run: |
          echo "Testing build process..."
          pnpm run docs:build
          echo "Build test completed successfully"

      - name: Verify build output
        run: |
          echo "Verifying build output..."
          ls -la docs/.vuepress/dist/
          echo "Build output verified"

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.5.2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.6.0'
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          echo "Installing dependencies for production build..."
          pnpm install --no-frozen-lockfile
          echo "Production dependencies installed"

      - name: Build VuePress site
        run: |
          echo "Building VuePress site..."
          pnpm run docs:full-check
          echo "Full deployment check completed successfully"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vuepress/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Verify deployment
        run: |
          echo "Deployment completed successfully!"
          echo "Site URL: ${{ steps.deployment.outputs.page_url }}"

